---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeek-live-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: zeek-live-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: zeek-live-deployment
    spec:
      containers:
      - name: zeek-live-container
        image: ghcr.io/idaholab/malcolm/zeek:23.05.0
        imagePullPolicy: Always
        stdin: false
        tty: true
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
              - SYS_RESOURCE
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: zeek-env
          - secretRef:
              name: zeek-secret-env
          - configMapRef:
              name: zeek-live-env
          - configMapRef:
              name: pcap-capture-env
        env:
          - name: ZEEK_DISABLED
            value: "true"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: zeek-live-var-local-catrust-volume
      volumes:
        - name: zeek-live-var-local-catrust-volume
          configMap:
            name: var-local-catrust
