version: '3.7'

services:
  opensearch:
    image: opensearchproject/opensearch:1.0.0
    restart: "no"
    environment:
      logger.level : 'INFO'
      bootstrap.memory_lock : 'true'
      OPENSEARCH_JAVA_OPTS : '-Xms4g -Xmx4g -Xss256k -Djava.security.egd=file:/dev/./urandom'
      discovery.type : 'single-node'
      cluster.routing.allocation.disk.threshold_enabled : 'false'
      cluster.routing.allocation.node_initial_primaries_recoveries : 8
    expose:
      - 9200
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 30s
    network_mode: host
  arkime:
    build:
      context: .
      dockerfile: Dockerfiles/arkime.Dockerfile
    image: arkimetest:latest
    restart: "no"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - opensearch
    expose:
      - 8000
      - 8005
      - 8081
    network_mode: host
    command: tail -F /dev/null
