name: Adds all issues that don't include the 'training' label to Malcolm project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/idaholab/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: training
          label-operator: NOT
